"""Mock LLM provider.

This provider is intended for local development and testing. It implements the
LLMProvider interface without making any external API calls.

The mock provider produces deterministic responses, making it suitable for:

- Unit tests
- Integration tests
- Local development
- CI pipelines

It mirrors the behaviour of the real provider by streaming tokens and emitting
a final StreamChunk containing token usage statistics.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterator
from typing import Any

from app.core.config import Settings
from app.services.llm.base import LLMProvider
from app.services.llm.models import StreamChunk, TokenUsage


class MockProvider(LLMProvider):
    """Mock implementation of the LLM provider."""

    DEFAULT_RESPONSE = (
        "Hello! This is a mock response generated by the CRM Copilot "
        "MockProvider."
    )

    def __init__(self, settings: Settings):
        super().__init__(settings)

    async def stream(
        self,
        messages: list[dict[str, Any]],
        model: str | None = None,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a deterministic response.

        Args:
            messages:
                Provider-ready messages. Only used for token estimation.

            model:
                Optional model override.

        Yields:
            StreamChunk objects.
        """

        response = self.DEFAULT_RESPONSE

        # Stream word-by-word to emulate real token streaming.
        words = response.split()

        for index, word in enumerate(words):
            await asyncio.sleep(0.02)

            token = word
            if index != len(words) - 1:
                token += " "

            yield StreamChunk.token_chunk(token)

        prompt_tokens = sum(
            len(msg.get("content", "").split())
            for msg in messages
        )

        completion_tokens = len(words)

        usage = TokenUsage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            model=model or "mock-model",
        )

        yield StreamChunk.final_chunk(
            finish_reason="stop",
            usage=usage,
        )

    async def complete(
        self,
        messages: list[dict[str, Any]],
        model: str | None = None,
    ) -> str:
        """Return a deterministic completion."""

        await asyncio.sleep(0.05)

        return self.DEFAULT_RESPONSE