"""add agent_action table

Hand-written rather than autogenerated. `alembic revision --autogenerate`
produced 422 lines here: besides this table it wanted to drop the
`document_chunks` ivfflat vector index, several foreign keys on
`knowledge_documents` and `prompt`, and to re-type a number of columns. That is
pre-existing drift between the models and the live schema, unrelated to this
feature, and applying it would be destructive. Only the new table is kept.

The drift itself is worth a separate look; it is not this migration's job.

Revision ID: 787be77fddb8
Revises: 45c38c0fad33
Create Date: 2026-09-20
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "787be77fddb8"
down_revision: Union[str, Sequence[str], None] = "45c38c0fad33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "agent_action",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
            comment="Tenant isolation. Every query filters on this.",
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "conversation_id",
            sa.UUID(),
            nullable=True,
            comment="Where the proposal was made. Null once the conversation goes.",
        ),
        sa.Column(
            "proposed_by_user_id",
            sa.UUID(),
            nullable=False,
            comment="Whose turn produced the proposal. Not the approver.",
        ),
        sa.Column(
            "action_type",
            sa.Enum(
                "CREATE_TASK",
                "UPDATE_TASK_STATUS",
                "CREATE_CONTACT",
                "UPDATE_CONTACT",
                "UPDATE_OPPORTUNITY_STAGE",
                name="agent_action_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Validated against a per-type schema before execution.",
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=True,
            comment="The agent's stated rationale, shown to the approver.",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXECUTED",
                "FAILED",
                name="agent_action_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "decided_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="The human who approved or rejected. Never the agent.",
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_entity_type", sa.String(), nullable=True),
        sa.Column("result_entity_id", sa.UUID(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "correlation_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Joins the proposal and its outcome in the audit log.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversation.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organization.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"], ["user.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_agent_action_org_id"), "agent_action", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_action_tenant_id"),
        "agent_action",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_action_tenant_status",
        "agent_action",
        ["tenant_id", "status"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_agent_action_tenant_status", table_name="agent_action")
    op.drop_index(op.f("ix_agent_action_tenant_id"), table_name="agent_action")
    op.drop_index(op.f("ix_agent_action_org_id"), table_name="agent_action")
    op.drop_table("agent_action")

    # create_table emits the enum types; drop_table does not remove them.
    sa.Enum(name="agent_action_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="agent_action_type").drop(op.get_bind(), checkfirst=True)
