"""create CRM core tables

Revision ID: a544e3a513a2
Revises: b2f1c6e7f9a1
Create Date: 2026-06-19 01:37:38.804865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a544e3a513a2'
down_revision: Union[str, Sequence[str], None] = 'b2f1c6e7f9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – links company to its organization'),
    sa.Column('name', sa.String(), nullable=False, comment='Company name'),
    sa.Column('industry', sa.String(), nullable=True, comment='Industry the company operates in'),
    sa.Column('website', sa.String(), nullable=True, comment='Company website URL'),
    sa.Column('phone', sa.String(), nullable=True, comment='Company phone number'),
    sa.Column('email', sa.String(), nullable=True, comment='Company contact email'),
    sa.Column('address', sa.String(), nullable=True, comment='Company address'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of company creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last company update'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_org_id'), 'company', ['org_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – links note to its organization'),
    sa.Column('entity_type', sa.Enum('company', 'contact', 'opportunity', name='note_entity_type'), nullable=False, comment='Entity type this note is attached to (company, contact, opportunity)'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='PK of the attached entity – no FK enforced'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full text content of the note'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of note creation (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of the last update to the note (UTC)'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_org_id'), 'note', ['org_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – links contact to its organization'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='FK → company.id – links contact to its company'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Contact first name'),
    sa.Column('last_name', sa.String(), nullable=False, comment='Contact last name'),
    sa.Column('email', sa.String(), nullable=True, comment='Contact email address'),
    sa.Column('phone', sa.String(), nullable=True, comment='Contact phone number'),
    sa.Column('job_title', sa.String(), nullable=True, comment='Contact job title'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of contact creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last contact update'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_company_id'), 'contact', ['company_id'], unique=False)
    op.create_index(op.f('ix_contact_org_id'), 'contact', ['org_id'], unique=False)
    op.create_table('opportunity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – links opportunity to its organization'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='FK → company.id – links opportunity to its company'),
    sa.Column('owner_user_id', sa.UUID(), nullable=False, comment='FK → user.id – user that owns the opportunity'),
    sa.Column('title', sa.String(), nullable=False, comment='Opportunity title'),
    sa.Column('stage', sa.Enum('LEAD', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', name='opportunity_stage'), nullable=False, comment='Sales pipeline stage'),
    sa.Column('probability', sa.Integer(), nullable=True, comment='Probability (0‑100) that the opportunity will close'),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True, comment='Monetary value of the opportunity'),
    sa.Column('expected_close_date', sa.Date(), nullable=True, comment='Expected close date (optional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of opportunity creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last opportunity update'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_company_id'), 'opportunity', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunity_org_id'), 'opportunity', ['org_id'], unique=False)
    op.create_index(op.f('ix_opportunity_owner_user_id'), 'opportunity', ['owner_user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – links task to its organization'),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=False, comment='FK → user.id – user responsible for the task'),
    sa.Column('entity_type', sa.Enum('company', 'contact', 'opportunity', name='task_entity_type'), nullable=True, comment='Optional entity type this task is attached to (company, contact, opportunity)'),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='Optional PK of the attached entity – no FK enforced'),
    sa.Column('title', sa.String(), nullable=False, comment='Task title – required'),
    sa.Column('description', sa.Text(), nullable=True, comment='Longer description of the task (optional)'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='task_status'), server_default=sa.text("'PENDING'"), nullable=False, comment='Current status of the task'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority'), server_default=sa.text("'MEDIUM'"), nullable=False, comment='Task priority level'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Optional task due date'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of task creation (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of the last update to the task (UTC)'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assigned_to_user_id'), 'task', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_task_org_id'), 'task', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_org_id'), table_name='task')
    op.drop_index(op.f('ix_task_assigned_to_user_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_opportunity_owner_user_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_org_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_company_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_contact_org_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_company_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_note_org_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_company_org_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
