"""Create tenant, organization, user tables and extensions

Revision ID: a8617753f0e8
Revises: 
Create Date: 2026-06-13 19:01:33.610316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8617753f0e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### extensions (must run before any table that uses gen_random_uuid) ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Primary key – generated by PostgreSQL pgcrypto'),
    sa.Column('name', sa.String(), nullable=False, comment='Human‑readable tenant name'),
    sa.Column('subdomain', sa.String(), nullable=False, comment='Unique sub‑domain used for tenant isolation (e.g. abc.mycrm.com)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp of tenant creation'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Primary key'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='FK → tenant.id – enforces tenant isolation'),
    sa.Column('name', sa.String(), nullable=False, comment='Organization name'),
    sa.Column('domain', sa.String(), nullable=True, comment='Optional custom domain for the org'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp of organization creation'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_tenant_id'), 'organization', ['tenant_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False, comment='Primary key'),
    sa.Column('org_id', sa.UUID(), nullable=False, comment='FK → organization.id – indirect tenant link'),
    sa.Column('email', sa.String(), nullable=False, comment='User email address – unique across all tenants'),
    sa.Column('password_hash', sa.String(), nullable=False, comment="Bcrypt hash of the user's password"),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', name='user_role'), nullable=False, comment='Role within the organization (enum‑like)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp of user creation'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_organization_tenant_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('tenant')
    # ### enum cleanup ###
    op.execute("DROP TYPE IF EXISTS user_role")
    # ### end Alembic commands ###
