"""sync column comments with models

The models declared column comments that the live schema never had, so
`alembic revision --autogenerate` proposed setting all 24 of them on every
run. That noise, together with a set of indexes and foreign keys that existed
only in migrations and not in the models, made autogenerate output roughly 420
lines of mostly-destructive diff -- including dropping the document_chunks
ivfflat vector index. Migrations had to be hand-written as a result.

The structural half was fixed by declaring the missing indexes, foreign-key
ondelete rules and column types in the models. This migration closes the other
half by writing the comments the models describe into the database. It changes
no types, nullability, defaults or constraints: every operation sets only
`comment`, and `existing_*` arguments are context that alembic emits.

After this, autogenerate reports no drift.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be95217572f6'
down_revision: Union[str, Sequence[str], None] = '787be77fddb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('knowledge_documents', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('prompt', 'id',
               existing_type=sa.UUID(),
               comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('prompt', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK → tenant.id',
               existing_nullable=False)
    op.alter_column('prompt', 'org_id',
               existing_type=sa.UUID(),
               comment='FK → organization.id',
               existing_nullable=False)
    op.alter_column('prompt', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Unique prompt name (e.g. crm_chat)',
               existing_nullable=False)
    op.alter_column('prompt', 'category',
               existing_type=postgresql.ENUM('system', 'agent', 'rag', 'tool', 'summarization', 'classification', 'action', 'custom', name='prompt_category'),
               comment='Prompt category',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::prompt_category"))
    op.alter_column('prompt', 'description',
               existing_type=sa.TEXT(),
               comment='Prompt description',
               existing_nullable=True)
    op.alter_column('prompt', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Prompt creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prompt', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Prompt last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prompt_version', 'id',
               existing_type=sa.UUID(),
               comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('prompt_version', 'prompt_id',
               existing_type=sa.UUID(),
               comment='FK → prompt.id',
               existing_nullable=False)
    op.alter_column('prompt_version', 'version',
               existing_type=sa.INTEGER(),
               comment='Prompt version number',
               existing_nullable=False)
    op.alter_column('prompt_version', 'description',
               existing_type=sa.TEXT(),
               comment='Description of this prompt version',
               existing_nullable=True)
    op.alter_column('prompt_version', 'template',
               existing_type=sa.TEXT(),
               comment='Prompt template (Jinja2)',
               existing_nullable=False)
    op.alter_column('prompt_version', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Required template variables',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_version', 'llm_model',
               existing_type=sa.TEXT(),
               comment='Preferred LLM model',
               existing_nullable=True)
    op.alter_column('prompt_version', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Default temperature',
               existing_nullable=False,
               existing_server_default=sa.text('0.2'))
    op.alter_column('prompt_version', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Default top_p',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('prompt_version', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='Maximum output tokens',
               existing_nullable=True)
    op.alter_column('prompt_version', 'response_format',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Expected response format',
               existing_nullable=True)
    op.alter_column('prompt_version', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional prompt configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('prompt_version', 'created_by',
               existing_type=sa.UUID(),
               comment='FK → user.id',
               existing_nullable=True)
    op.alter_column('prompt_version', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Prompt version creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_version', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Prompt version creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prompt_version', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → user.id',
               existing_nullable=True)
    op.alter_column('prompt_version', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional prompt configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('prompt_version', 'response_format',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Expected response format',
               existing_nullable=True)
    op.alter_column('prompt_version', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum output tokens',
               existing_nullable=True)
    op.alter_column('prompt_version', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Default top_p',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('prompt_version', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Default temperature',
               existing_nullable=False,
               existing_server_default=sa.text('0.2'))
    op.alter_column('prompt_version', 'llm_model',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Preferred LLM model',
               existing_nullable=True)
    op.alter_column('prompt_version', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Required template variables',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_version', 'template',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Prompt template (Jinja2)',
               existing_nullable=False)
    op.alter_column('prompt_version', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Description of this prompt version',
               existing_nullable=True)
    op.alter_column('prompt_version', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Prompt version number',
               existing_nullable=False)
    op.alter_column('prompt_version', 'prompt_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → prompt.id',
               existing_nullable=False)
    op.alter_column('prompt_version', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('prompt', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Prompt last update timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prompt', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Prompt creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prompt', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Prompt description',
               existing_nullable=True)
    op.alter_column('prompt', 'category',
               existing_type=postgresql.ENUM('system', 'agent', 'rag', 'tool', 'summarization', 'classification', 'action', 'custom', name='prompt_category'),
               comment=None,
               existing_comment='Prompt category',
               existing_nullable=False,
               existing_server_default=sa.text("'system'::prompt_category"))
    op.alter_column('prompt', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Unique prompt name (e.g. crm_chat)',
               existing_nullable=False)
    op.alter_column('prompt', 'org_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → organization.id',
               existing_nullable=False)
    op.alter_column('prompt', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → tenant.id',
               existing_nullable=False)
    op.alter_column('prompt', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('knowledge_documents', 'id',
               existing_type=sa.UUID(),
               comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('document_chunks', 'id',
               existing_type=sa.UUID(),
               comment='Primary key – generated by PostgreSQL pgcrypto',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###
