"""add tenant_id to company

Revision ID: c97b2553d48f
Revises: 42c06b8d0a9f
Create Date: 2026-06-23 02:16:21.860864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c97b2553d48f'
down_revision: Union[str, Sequence[str], None] = '42c06b8d0a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tenant_id', sa.UUID(), nullable=False, comment='FK → tenant.id'))
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'company', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('user', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Direct tenant ownership',
               existing_nullable=False)
    op.alter_column('user', 'org_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → organization.id – indirect tenant link',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='User email address – unique across all tenants',
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Bcrypt hash of the user's password",
               existing_nullable=False)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', name='user_role'),
               comment=None,
               existing_comment='Role within the organization (enum‑like)',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of user creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of user creation',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', name='user_role'),
               comment='Role within the organization (enum‑like)',
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(),
               comment="Bcrypt hash of the user's password",
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               comment='User email address – unique across all tenants',
               existing_nullable=False)
    op.alter_column('user', 'org_id',
               existing_type=sa.UUID(),
               comment='FK → organization.id – indirect tenant link',
               existing_nullable=False)
    op.alter_column('user', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Direct tenant ownership',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_column('company', 'tenant_id')
    # ### end Alembic commands ###
