"""Add audit_logs table and audit_action enum

Revision ID: xxxx_add_audit_logs_table
Revises: a8617753f0e8
Create Date: 2026-06-24 12:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d273e1ab7816"
down_revision: Union[str, Sequence[str], None] = "c273e1ad7166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create audit_action enum and audit_logs table with indexes and constraints."""
    # ### commands auto generated by Alembic - please adjust! ###
    audit_action_enum = postgresql.ENUM(
        "CREATE",
        "UPDATE",
        "DELETE",
        "READ",
        "LOGIN",
        "LOGOUT",
        "AI_PROMPT",
        "AI_TOOL_CALL",
        "APPROVAL_REQUESTED",
        "APPROVAL_GRANTED",
        "APPROVAL_REJECTED",
        name="audit_action",
        create_type=False,
    )
    audit_action_enum.create(op.get_bind(), checkfirst=True)
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("(gen_random_uuid())"), nullable=False, comment="Primary key – generated by PostgreSQL pgcrypto"),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("action", audit_action_enum, nullable=False),
        sa.Column("before_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False, server_default="USER"),
        sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_tenant_created","audit_logs",["tenant_id", "created_at"],unique=False)
    op.create_index("ix_audit_logs_tenant_entity", "audit_logs", ["tenant_id", "entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_logs_tenant_user", "audit_logs", ["tenant_id", "user_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_correlation_id","audit_logs",["correlation_id"],unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop audit_logs table and audit_action enum."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_user", table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_correlation_id", table_name="audit_logs")
    op.drop_table("audit_logs")
    audit_action_enum = postgresql.ENUM(
        "CREATE",
        "UPDATE",
        "DELETE",
        "READ",
        "LOGIN",
        "LOGOUT",
        "AI_PROMPT",
        "AI_TOOL_CALL",
        "APPROVAL_REQUESTED",
        "APPROVAL_GRANTED",
        "APPROVAL_REJECTED",
        name="audit_action",
        create_type=False,
    )
    audit_action_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
