"""Add knowledge_documents and document_chunks tables for RAG pipeline

Revision ID: 001_add_knowledge_document_table
Revises: d273e1ab7816
Create Date: 2026-07-04 12:00:00.000000
"""

from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e273d1bc9120"
down_revision: Union[str, Sequence[str], None] = "7e4aa5d78f16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create processing_status enum, knowledge_documents and document_chunks tables."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Create processing_status enum
    processing_status_enum = postgresql.ENUM(
        "UPLOADED",
        "PARSING",
        "CHUNKING",
        "EMBEDDING",
        "READY",
        "FAILED",
        name="processing_status",
        create_type=False,
    )
    processing_status_enum.create(op.get_bind(), checkfirst=True)

    # Create knowledge_documents table
    op.create_table(
        "knowledge_documents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
            comment="Primary key – generated by PostgreSQL pgcrypto",
        ),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("document_type", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("processing_status", processing_status_enum, nullable=False, server_default="UPLOADED"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_knowledge_documents_tenant_id", "knowledge_documents", ["tenant_id"], unique=False)
    op.create_index("ix_knowledge_documents_organization_id", "knowledge_documents", ["organization_id"], unique=False)
    op.create_index("ix_knowledge_documents_status", "knowledge_documents", ["processing_status"], unique=False)
    op.create_index("ix_knowledge_documents_tenant_status", "knowledge_documents", ["tenant_id", "processing_status"])

    # Create document_chunks table
    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
            comment="Primary key – generated by PostgreSQL pgcrypto",
        ),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenant.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_document_chunks_tenant_id", "document_chunks", ["tenant_id"], unique=False)
    op.create_index("ix_document_chunks_document_id", "document_chunks", ["document_id"], unique=False)
    op.create_index("ix_document_chunks_chunk_index", "document_chunks", ["chunk_index"], unique=False)
    op.create_index("ix_document_chunks_tenant_document", "document_chunks", ["tenant_id", "document_id"])

    # Create vector index for similarity search (using ivfflat)
    # Vector dimension is determined by embedding provider (e.g., 1536 for OpenAI)
    #Default dimension = 1536, Changing providers requires a migration.
    op.execute(""" CREATE INDEX ix_document_chunks_embedding ON document_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100) """)


def downgrade() -> None:
    """Drop document_chunks, knowledge_documents tables and processing_status enum."""
    op.drop_index("ix_document_chunks_embedding", table_name="document_chunks")
    op.drop_index("ix_document_chunks_chunk_index", table_name="document_chunks")
    op.drop_index("ix_document_chunks_document_id", table_name="document_chunks")
    op.drop_index("ix_document_chunks_tenant_id", table_name="document_chunks")
    op.drop_index("ix_document_chunks_tenant_document", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_knowledge_documents_status", table_name="knowledge_documents")
    op.drop_index("ix_knowledge_documents_organization_id", table_name="knowledge_documents")
    op.drop_index("ix_knowledge_documents_tenant_id", table_name="knowledge_documents")
    op.drop_index("ix_knowledge_documents_tenant_status", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    processing_status_enum = postgresql.ENUM(
        "UPLOADED",
        "PARSING",
        "CHUNKING",
        "EMBEDDING",
        "READY",
        "FAILED",
        name="processing_status",
        create_type=False,
    )
    processing_status_enum.drop(op.get_bind(), checkfirst=True)
    # Note: we don't drop the vector extension as other objects may depend on it
    # op.execute("DROP EXTENSION IF EXISTS vector")