"""
Integration tests for AI Agent Retrieval Observability.

These tests verify that executing the AI Agent preserves the
Retrieval Observability pipeline introduced in Spec 006.
"""

from __future__ import annotations

from unittest.mock import AsyncMock
from uuid import uuid4

import pytest

from app.agent.service import AgentService
from app.agent.state import AgentState


@pytest.mark.asyncio
async def test_agent_creates_retrieval_metadata() -> None:
    """
    The final AgentState should contain retrieval metadata after
    successful retrieval.
    """

    expected_state: AgentState = {
        "conversation_id": uuid4(),
        "tenant_id": uuid4(),
        "user_id": uuid4(),
        "query": "Explain Retrieval Observability",
        "messages": [],
        "retrieved_documents": ["doc-1", "doc-2"],
        "retrieval_metadata": {
            "retrieved_count": 2,
            "latency_ms": 18,
        },
        "prompt": "Prompt",
        "response": "Answer",
        "citations": [],
        "usage": {},
        "errors": [],
    }

    runner = AsyncMock()
    runner.run.return_value = expected_state

    service = AgentService(runner)

    result = await service.run(
        conversation_id=expected_state["conversation_id"],
        tenant_id=expected_state["tenant_id"],
        user_id=expected_state["user_id"],
        query=expected_state["query"],
    )

    assert result["retrieval_metadata"]["retrieved_count"] == 2
    assert result["retrieval_metadata"]["latency_ms"] == 18


@pytest.mark.asyncio
async def test_agent_handles_empty_retrieval() -> None:
    """
    The agent should complete successfully even when no
    documents are retrieved.
    """

    expected_state: AgentState = {
        "conversation_id": uuid4(),
        "tenant_id": uuid4(),
        "user_id": uuid4(),
        "query": "No matching documents",
        "messages": [],
        "retrieved_documents": [],
        "retrieval_metadata": {
            "retrieved_count": 0,
        },
        "prompt": "Prompt",
        "response": "No relevant documents were found.",
        "citations": [],
        "usage": {},
        "errors": [],
    }

    runner = AsyncMock()
    runner.run.return_value = expected_state

    service = AgentService(runner)

    result = await service.run(
        conversation_id=expected_state["conversation_id"],
        tenant_id=expected_state["tenant_id"],
        user_id=expected_state["user_id"],
        query=expected_state["query"],
    )

    assert result["retrieved_documents"] == []
    assert result["retrieval_metadata"]["retrieved_count"] == 0


@pytest.mark.asyncio
async def test_agent_returns_citations_after_retrieval() -> None:
    """
    Citations generated by the finish node should be preserved.
    """

    expected_state: AgentState = {
        "conversation_id": uuid4(),
        "tenant_id": uuid4(),
        "user_id": uuid4(),
        "query": "Explain embeddings",
        "messages": [],
        "retrieved_documents": ["doc-1"],
        "retrieval_metadata": {
            "retrieved_count": 1,
        },
        "prompt": "Prompt",
        "response": "Embeddings convert text into vectors.",
        "citations": [
            {
                "title": "Embeddings Guide",
                "chunk_index": 0,
            }
        ],
        "usage": {},
        "errors": [],
    }

    runner = AsyncMock()
    runner.run.return_value = expected_state

    service = AgentService(runner)

    result = await service.run(
        conversation_id=expected_state["conversation_id"],
        tenant_id=expected_state["tenant_id"],
        user_id=expected_state["user_id"],
        query=expected_state["query"],
    )

    assert len(result["citations"]) == 1
    assert result["citations"][0]["title"] == "Embeddings Guide"


@pytest.mark.asyncio
async def test_agent_propagates_retrieval_errors() -> None:
    """
    Retrieval errors should be preserved in the final AgentState.
    """

    expected_state: AgentState = {
        "conversation_id": uuid4(),
        "tenant_id": uuid4(),
        "user_id": uuid4(),
        "query": "Trigger failure",
        "messages": [],
        "retrieved_documents": [],
        "retrieval_metadata": {},
        "prompt": "",
        "response": None,
        "citations": [],
        "usage": {},
        "errors": [
            {
                "node": "retrieve",
                "message": "Similarity search failed",
            }
        ],
    }

    runner = AsyncMock()
    runner.run.return_value = expected_state

    service = AgentService(runner)

    result = await service.run(
        conversation_id=expected_state["conversation_id"],
        tenant_id=expected_state["tenant_id"],
        user_id=expected_state["user_id"],
        query=expected_state["query"],
    )

    assert len(result["errors"]) == 1
    assert result["errors"][0]["node"] == "retrieve"


@pytest.mark.asyncio
async def test_agent_preserves_usage_metadata() -> None:
    """
    Token usage returned by the graph should be preserved.
    """

    expected_state: AgentState = {
        "conversation_id": uuid4(),
        "tenant_id": uuid4(),
        "user_id": uuid4(),
        "query": "Hello",
        "messages": [],
        "retrieved_documents": [],
        "retrieval_metadata": {},
        "prompt": "Prompt",
        "response": "Hello!",
        "citations": [],
        "usage": {
            "prompt_tokens": 12,
            "completion_tokens": 18,
            "total_tokens": 30,
            "model": "mock-model",
        },
        "errors": [],
    }

    runner = AsyncMock()
    runner.run.return_value = expected_state

    service = AgentService(runner)

    result = await service.run(
        conversation_id=expected_state["conversation_id"],
        tenant_id=expected_state["tenant_id"],
        user_id=expected_state["user_id"],
        query=expected_state["query"],
    )

    assert result["usage"]["total_tokens"] == 30
    assert result["usage"]["model"] == "mock-model"