"""Pydantic v2 schemas for the ``Company`` entity.

All response schemas include ``id``, ``created_at`` and ``updated_at`` fields.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Base schema – shared fields for create/read operations
# ---------------------------------------------------------------------------

class CompanyBase(BaseModel):
    name: str = Field(..., description="Company name")
    industry: Optional[str] = Field(None, description="Industry the company operates in")
    website: Optional[str] = Field(None, description="Company website URL")
    phone: Optional[str] = Field(None, description="Company phone number")
    email: Optional[str] = Field(None, description="Company contact email")
    address: Optional[str] = Field(None, description="Company address")

    model_config = ConfigDict(from_attributes=True)

# ---------------------------------------------------------------------------
# Create schema – used for POST /companies
# ---------------------------------------------------------------------------

class CompanyCreate(CompanyBase):
    """Fields required to create a Company.

    ``id`` and tenant information are omitted – they are generated by the DB and
    derived from the authentication context.
    """

    pass

# ---------------------------------------------------------------------------
# Update schema – all fields optional for PATCH /companies/{id}
# ---------------------------------------------------------------------------

class CompanyUpdate(BaseModel):
    name: Optional[str] = Field(None, description="Company name")
    industry: Optional[str] = Field(None, description="Industry the company operates in")
    website: Optional[str] = Field(None, description="Company website URL")
    phone: Optional[str] = Field(None, description="Company phone number")
    email: Optional[str] = Field(None, description="Company contact email")
    address: Optional[str] = Field(None, description="Company address")

    model_config = ConfigDict(from_attributes=True)

# ---------------------------------------------------------------------------
# Response schema – returned by GET endpoints (ORM serialization enabled)
# ---------------------------------------------------------------------------

class CompanyResponse(CompanyBase):
    id: UUID = Field(..., description="Primary key (UUID) of the company")
    created_at: datetime = Field(..., description="Timestamp of company creation")
    updated_at: datetime = Field(..., description="Timestamp of last company update")