"""AuditLog model – immutable audit trail for all CRM actions.

This model follows the specification in `specs/003-audit-activity.md`.
It stores audit events in an append‑only table with JSONB columns for
flexible payloads and includes fields for future AI workflow support.
"""

from __future__ import annotations

import datetime
import uuid
from enum import Enum
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID

from packages.database.models.base import Base
from sqlalchemy import (
    Column,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    String,
    func,
)


class AuditAction(str, Enum):
    """Enumeration of possible audit actions.

    The list is deliberately exhaustive for the current phase; additional
    actions can be added later without a database migration because the
    column uses a PostgreSQL ``ENUM`` type that will be altered if the enum
    definition changes.
    """

    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    READ = "READ"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    AI_PROMPT = "AI_PROMPT"
    AI_TOOL_CALL = "AI_TOOL_CALL"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"


class AuditLog(Base):
    """Immutable audit log record.

    All fields are write‑once; the application must never issue UPDATE or
    DELETE statements against this table (the repository layer will raise
    ``NotImplementedError`` for such operations).
    """

    __tablename__ = "audit_logs"

    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )

    org_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="FK → organization.id – optional for system actions",
    )

    user_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="FK → user.id – actor that performed the action",
    )

    # Polymorphic target entity information
    entity_type = Column(String(50), nullable=False, comment="Target entity type")
    entity_id = Column(PGUUID(as_uuid=True), nullable=False, comment="Target entity UUID")

    action = Column(SAEnum(AuditAction, name="audit_action"), nullable=False)

    before_values = Column(JSONB, nullable=True)
    after_values = Column(JSONB, nullable=True)

    ip_address = Column(String(45), nullable=True)
    user_agent = Column(String(255), nullable=True)

    # Future‑ready fields for AI workflows
    actor_type = Column(String(30), nullable=False, server_default="USER", comment="e.g. 'human', 'ai_agent'")
    correlation_id = Column(PGUUID(as_uuid=True), nullable=True, comment="Correlation ID for related events")

    event_metadata = Column(JSONB, nullable=True)

    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of audit event creation",
    )

    __table_args__ = (
        Index("ix_audit_logs_tenant_entity", "tenant_id", "entity_type", "entity_id"),
        Index("ix_audit_logs_tenant_user", "tenant_id", "user_id"),
        Index("ix_audit_logs_created_at", "tenant_id", "created_at"),
    )
