"""Company model – belongs to an Organization."""

from __future__ import annotations

import datetime

from sqlalchemy import Column, DateTime, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base
from packages.database.models.organization import Organization


class Company(Base):
    """Company entity under an organization."""

    __tablename__ = "company"

    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )
    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )
    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id – links company to its organization",
    )
    name: str = Column(String, nullable=False, comment="Company name")
    industry: str | None = Column(
        String, nullable=True, comment="Industry the company operates in"
    )
    website: str | None = Column(
        String, nullable=True, comment="Company website URL"
    )
    phone: str | None = Column(
        String, nullable=True, comment="Company phone number"
    )
    email: str | None = Column(
        String, nullable=True, comment="Company contact email"
    )
    address: str | None = Column(
        String, nullable=True, comment="Company address"
    )
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of company creation",
    )
    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of last company update",
    )

    # Relationships
    organization = relationship(
        "Organization", backref="companies", lazy="joined"
    )