"""Contact model – belongs to an Organization and a Company."""

from __future__ import annotations

import datetime

from sqlalchemy import Column, DateTime, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base
from packages.database.models.organization import Organization
from packages.database.models.company import Company


class Contact(Base):
    """Contact entity associated with an organization and a company."""

    __tablename__ = "contact"

    # Primary key – UUID generated by PostgreSQL pgcrypto
    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    # Direct link to the parent organization (required for tenant_scoped_query)
    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id – links contact to its organization",
    )

    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )

    # Direct link to the parent company (required for business rules)
    company_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("company.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → company.id – links contact to its company",
    )

    # Required personal details
    first_name: str = Column(String, nullable=False, comment="Contact first name")
    last_name: str = Column(String, nullable=False, comment="Contact last name")

    # optional fields
    email: str | None = Column(String, nullable=True, comment="Contact email address")
    phone: str | None = Column(String, nullable=True, comment="Contact phone number")
    job_title: str | None = Column(String, nullable=True, comment="Contact job title")

    # Timestamp columns – identical to Organization/User conventions
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of contact creation",
    )
    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of last contact update",
    )

    # --------------------------------------------------------------------- #
    # Relationships
    # --------------------------------------------------------------------- #
    organization = relationship(
        "Organization", backref="contacts", lazy="joined"
    )
    company = relationship(
        "Company", backref="contacts", lazy="joined"
    )