"""Note model – belongs to an Organization and can be attached to any core CRM entity.

The design follows the exact conventions used by the existing models
(Company, Contact, Opportunity, Task):
* Singular, lower‑case table name.
* PostgreSQL‑generated UUID primary key.
* `org_id` for tenant‑scoped queries (via `tenant_scoped_query`).
* Polymorphic attachment expressed by the `entity_type` / `entity_id` pair –
  no foreign‑key constraint on `entity_id` and no SQLAlchemy polymorphic mapping,
  per the spec. Validation is performed in the service layer.
* Timestamp columns are timezone‑aware and managed by the DB.
* A named PostgreSQL enum (`note_entity_type`) is used for the attachment type.
"""

from __future__ import annotations

import datetime

from sqlalchemy import Column, DateTime, Enum, ForeignKey, Text, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base

# ---------------------------------------------------------------------------
# Named PostgreSQL enum for the polymorphic attachment target.
# ---------------------------------------------------------------------------
note_entity_type = Enum(
    "company",
    "contact",
    "opportunity",
    name="note_entity_type",
)


class Note(Base):
    """CRM note entity – attached to a Company, Contact, or Opportunity.

    The `entity_type` / `entity_id` fields allow a note to be linked to any of the
    core CRM objects without a foreign‑key constraint, as required by the
    specification. Validation of the polymorphic relationship is performed in the
    service layer.
    """

    __tablename__ = "note"

    # ---------------------------------------------------------------------
    # Primary key – UUID generated by PostgreSQL pgcrypto
    # ---------------------------------------------------------------------
    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    # ---------------------------------------------------------------------
    # Tenant isolation – required by `tenant_scoped_query`
    # ---------------------------------------------------------------------
    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id – links note to its organization",
    )

    # ---------------------------------------------------------------------
    # Polymorphic attachment – required, but no FK constraints
    # ---------------------------------------------------------------------
    entity_type: str = Column(
        note_entity_type,
        nullable=False,
        comment="Entity type this note is attached to (company, contact, opportunity)",
    )
    entity_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        nullable=False,
        comment="PK of the attached entity – no FK enforced",
    )

    # ---------------------------------------------------------------------
    # Core content field
    # ---------------------------------------------------------------------
    content: str = Column(
        Text,
        nullable=False,
        comment="Full text content of the note",
    )

    # ---------------------------------------------------------------------
    # Audit timestamps (UTC, timezone‑aware)
    # ---------------------------------------------------------------------
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of note creation (UTC)",
    )
    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of the last update to the note (UTC)",
    )

    # ---------------------------------------------------------------------
    # Relationships – eager‑joined for convenience
    # ---------------------------------------------------------------------
    organization = relationship(
        "Organization", backref="notes", lazy="joined"
    )
