"""Opportunity model – belongs to an Organization, a Company and a User (owner)."""

from __future__ import annotations

import datetime
from decimal import Decimal

from sqlalchemy import Column, Date, DateTime, Enum, ForeignKey, Integer, Numeric, String, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base


class Opportunity(Base):
    """Opportunity entity within an organization."""

    __tablename__ = "opportunity"

    # Primary key – UUID generated by PostgreSQL pgcrypto
    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    # Direct link to the parent organization (required for tenant_scoped_query)
    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id – links opportunity to its organization",
    )

    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )

    # Direct link to the parent company
    company_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("company.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → company.id – links opportunity to its company",
    )

    # Owner user (sales rep, account manager, …)
    owner_user_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → user.id – user that owns the opportunity",
    )

    # Core fields
    title: str = Column(String, nullable=False, comment="Opportunity title")
    stage: str = Column(
        Enum(
            "LEAD",
            "QUALIFIED",
            "PROPOSAL",
            "NEGOTIATION",
            "WON",
            "LOST",
            name="opportunity_stage",
        ),
        nullable=False,
        comment="Sales pipeline stage",
    )
    probability: int | None = Column(
        Integer,
        nullable=True,
        comment="Probability (0‑100) that the opportunity will close",
    )
    # Monetary value – stored with fixed precision (12 total digits, 2 after decimal)
    value: Decimal | None = Column(
        Numeric(12, 2),
        nullable=True,
        comment="Monetary value of the opportunity",
    )
    expected_close_date: datetime.date | None = Column(
        Date,
        nullable=True,
        comment="Expected close date (optional)",
    )

    # Timestamp columns – same convention as Organization/User
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of opportunity creation",
    )
    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of last opportunity update",
    )

    # --------------------------------------------------------------------- #
    # Relationships
    # --------------------------------------------------------------------- #
    organization = relationship(
        "Organization", backref="opportunities", lazy="joined"
    )
    company = relationship(
        "Company", backref="opportunities", lazy="joined"
    )
    owner_user = relationship(
        "User", backref="owned_opportunities", lazy="joined"
    )



