"""PromptVersion model for Prompt Management."""

from __future__ import annotations

import datetime

from sqlalchemy import (
    Index,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base
from packages.database.models.prompt import Prompt


class PromptVersion(Base):
    """
    Immutable version of a Prompt.

    Every modification to a prompt creates a new PromptVersion.
    Existing versions are never updated.
    """

    __tablename__ = "prompt_version"

    __table_args__ = (
        UniqueConstraint(
            "prompt_id",
            "version",
            name="uq_prompt_version",
        ),
        Index("ix_prompt_version_version", "version"),
        Index("ix_prompt_version_created_by", "created_by"),
    )

    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    prompt_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("prompt.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → prompt.id",
    )

    version: int = Column(
        Integer,
        nullable=False,
        comment="Prompt version number",
    )

    description: str | None = Column(
        Text,
        nullable=True,
        comment="Description of this prompt version",
    )

    template: str = Column(
        Text,
        nullable=False,
        comment="Prompt template (Jinja2)",
    )

    variables = Column(
        JSONB,
        nullable=False,
        default=list,
        comment="Required template variables",
    )

    llm_model: str | None = Column(
        Text,
        nullable=True,
        comment="Preferred LLM model",
    )

    temperature: float = Column(
        Float,
        nullable=False,
        default=0.2,
        comment="Default temperature",
    )

    top_p: float = Column(
        Float,
        nullable=False,
        default=1.0,
        comment="Default top_p",
    )

    max_tokens: int | None = Column(
        Integer,
        nullable=True,
        comment="Maximum output tokens",
    )

    response_format = Column(
        JSONB,
        nullable=True,
        comment="Expected response format",
    )

    config = Column(
        JSONB,
        nullable=False,
        default=dict,
        comment="Additional prompt configuration",
    )

    created_by = Column(
        PGUUID(as_uuid=True),
        ForeignKey("user.id", ondelete="SET NULL"),
        nullable=True,
        comment="FK → user.id",
    )

    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Prompt version creation timestamp",
    )

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    prompt = relationship(
        "Prompt",
        back_populates="versions",
        foreign_keys=[prompt_id],
        lazy="joined",
    )

    creator = relationship(
        "User",
        lazy="joined",
    )

    def __repr__(self) -> str:
        return (
            f"<PromptVersion("
            f"id={self.id}, "
            f"prompt_id={self.prompt_id}, "
            f"version={self.version})>"
        )