"""Prompt model for Prompt Management."""

from __future__ import annotations

import datetime
from enum import Enum

from sqlalchemy import (
    Index,
    Column,
    DateTime,
    Enum as SQLEnum,
    ForeignKey,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base
from packages.database.models.organization import Organization


class PromptCategory(str, Enum):
    """Supported prompt categories."""

    SYSTEM = "system"
    AGENT = "agent"
    RAG = "rag"
    TOOL = "tool"
    SUMMARIZATION = "summarization"
    CLASSIFICATION = "classification"
    ACTION = "action"
    CUSTOM = "custom"


class Prompt(Base):
    """Logical prompt definition."""

    __tablename__ = "prompt"

    __table_args__ = (
        UniqueConstraint(
            "org_id",
            "name",
            name="uq_prompt_org_name",
        ),
        Index("ix_prompt_category", "category"),
    )

    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )

    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id",
    )

    name: str = Column(
        String(100),
        nullable=False,
        comment="Unique prompt name (e.g. crm_chat)",
    )

    category: PromptCategory = Column(
        SQLEnum(
            PromptCategory,
            name="prompt_category",
            values_callable=lambda enum: [e.value for e in enum],
        ),
        nullable=False,
        default=PromptCategory.SYSTEM,
        comment="Prompt category",
    )

    description: str | None = Column(
        Text,
        nullable=True,
        comment="Prompt description",
    )


    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Prompt creation timestamp",
    )

    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Prompt last update timestamp",
    )

    active_version_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("prompt_version.id", ondelete="SET NULL"),
        nullable=True,
    )

    

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------


    active_version = relationship(
        "PromptVersion",
        foreign_keys=[active_version_id],
        post_update=True,
    )

    organization = relationship(
        "Organization",
        back_populates="prompts",
    )

    versions = relationship(
        "PromptVersion",
        back_populates="prompt",
        cascade="all, delete-orphan",
        foreign_keys="PromptVersion.prompt_id",
        order_by="PromptVersion.version.desc()",
    )

    def __repr__(self) -> str:
        return (
            f"<Prompt(id={self.id}, "
            f"name='{self.name}', "
            f"category='{self.category.value}')>"
        )