"""Task model – belongs to an Organization and is assigned to a User.

The model follows the same conventions as the other CRM entities
(Company, Contact, Opportunity):
* PostgreSQL‑generated UUID primary key.
* `org_id` for tenant‑scoped queries (via `tenant_scoped_query`).
* Timestamp columns that are timezone‑aware and managed by the DB.
* Enum columns are defined with named Postgres enums so they can be
  re‑used in migrations and are self‑documenting.
* Polymorphic attachment to other CRM entities is expressed by the
  `entity_type` / `entity_id` pair – no foreign keys are created for
  `entity_id` and no SQLAlchemy polymorphic mapping is added, per the
  spec.
"""

from __future__ import annotations

import datetime

from sqlalchemy import (
    Column,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from packages.database.models.base import Base

# --------------------------------------------------------------------------- #
# Named PostgreSQL enums – these are created once and reused by migrations.
# --------------------------------------------------------------------------- #
task_status = Enum(
    "PENDING",
    "IN_PROGRESS",
    "COMPLETED",
    name="task_status",
)

task_priority = Enum(
    "LOW",
    "MEDIUM",
    "HIGH",
    name="task_priority",
)

task_entity_type = Enum(
    "company",
    "contact",
    "opportunity",
    name="task_entity_type",
)


class Task(Base):
    """CRM task entity – owned by an organization and assigned to a user.

    The `entity_type` / `entity_id` fields allow a task to be attached to
    any of the core CRM objects (Company, Contact, Opportunity) without
    creating foreign‑key constraints, as required by the specification.
    Validation of the polymorphic relationship is performed in the service
    layer.
    """

    __tablename__ = "task"

    # --------------------------------------------------------------------- #
    # Primary key – UUID generated by PostgreSQL pgcrypto
    # --------------------------------------------------------------------- #
    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )

    # --------------------------------------------------------------------- #
    # Tenant isolation – required by `tenant_scoped_query`
    # --------------------------------------------------------------------- #
    org_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("organization.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → organization.id – links task to its organization",
    )

    tenant_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → tenant.id",
    )

    # --------------------------------------------------------------------- #
    # Assignment
    # --------------------------------------------------------------------- #
    assigned_to_user_id: PGUUID = Column(
        PGUUID(as_uuid=True),
        ForeignKey("user.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK → user.id – user responsible for the task",
    )

    # --------------------------------------------------------------------- #
    # Polymorphic attachment – optional
    # --------------------------------------------------------------------- #
    entity_type: str | None = Column(
        task_entity_type,
        nullable=True,
        comment="Optional entity type this task is attached to (company, contact, opportunity)",
    )
    entity_id: PGUUID | None = Column(
        PGUUID(as_uuid=True),
        nullable=True,
        comment="Optional PK of the attached entity – no FK enforced",
    )

    # --------------------------------------------------------------------- #
    # Core fields
    # --------------------------------------------------------------------- #
    title: str = Column(String, nullable=False, comment="Task title – required")
    description: str | None = Column(
        Text, nullable=True, comment="Longer description of the task (optional)"
    )
    status: str = Column(
        task_status,
        nullable=False,
        server_default=text("'PENDING'"),
        comment="Current status of the task",
    )
    priority: str = Column(
        task_priority,
        nullable=False,
        server_default=text("'MEDIUM'"),
        comment="Task priority level",
    )
    due_date: datetime.date | None = Column(
        Date,
        nullable=True,
        comment="Optional task due date",
    )

    # --------------------------------------------------------------------- #
    # Audit timestamps
    # --------------------------------------------------------------------- #
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of task creation (UTC)",
    )
    updated_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp of the last update to the task (UTC)",
    )

    # --------------------------------------------------------------------- #
    # Relationships – eager‑joined for convenience
    # --------------------------------------------------------------------- #
    organization = relationship(
        "Organization", backref="tasks", lazy="joined"
    )
    assigned_user = relationship(
        "User", backref="assigned_tasks", lazy="joined"
    )
