"""Tenant model – top‑level tenant entity."""

from __future__ import annotations

import datetime

from sqlalchemy import Column, DateTime, String, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID

from packages.database.models.base import Base


class Tenant(Base):
    """Represents a tenant (customer) in the CRM system."""

    __tablename__ = "tenant"

    id: PGUUID = Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        comment="Primary key – generated by PostgreSQL pgcrypto",
    )
    name: str = Column(String, nullable=False, comment="Human‑readable tenant name")
    subdomain: str = Column(
        String,
        nullable=False,
        unique=True,
        comment="Unique sub‑domain used for tenant isolation (e.g. abc.mycrm.com)",
    )
    created_at: datetime.datetime = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Timestamp of tenant creation",
    )
