"""Shared models for the LLM service layer.

These lightweight dataclasses provide a provider-agnostic representation of
streaming chunks and token usage. They are intentionally independent of any
specific LLM provider (OpenAI, Anthropic, Gemini, etc.) and are shared across
the service layer.

Business logic (ChatService) consumes these models, while concrete providers
produce them.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional
from uuid import UUID


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Immutable token usage statistics for a single LLM request."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    model: Optional[str] = None

    @classmethod
    def empty(cls) -> "TokenUsage":
        """Return an empty usage object."""
        return cls(
            prompt_tokens=0,
            completion_tokens=0,
            total_tokens=0,
            model=None,
        )

    @classmethod
    def from_openai(cls, usage: Any, model: Optional[str] = None) -> "TokenUsage":
        """Create a TokenUsage from an OpenAI usage object.

        Args:
            usage:
                The ``response.usage`` object returned by the OpenAI SDK.
            model:
                The model name used for the request.

        Returns:
            TokenUsage populated with token counts.
        """
        if usage is None:
            return cls.empty()

        return cls(
            prompt_tokens=getattr(usage, "prompt_tokens", 0),
            completion_tokens=getattr(usage, "completion_tokens", 0),
            total_tokens=getattr(usage, "total_tokens", 0),
            model=model,
        )


@dataclass(slots=True)
class StreamChunk:
    """Represents one chunk emitted during streaming.

    Attributes:
        token:
            Incremental text token generated by the model.
            None indicates that no text was produced for this chunk.

        finish_reason:
            Finish reason returned by the provider
            (e.g. "stop", "length", "content_filter").

        usage:
            Final token usage statistics.

            During streaming this will normally be None.
            The final emitted chunk should contain the completed TokenUsage.

        conversation_id:
            ID of the conversation associated with this stream.

        message_id:
            ID of the assistant message (populated only on final chunk).
    """
    is_final: bool = False
    token: Optional[str] = None
    finish_reason: Optional[str] = None
    usage: Optional[TokenUsage] = None
    conversation_id: Optional[UUID] = None
    message_id: Optional[UUID] = None


    @classmethod
    def token_chunk(cls, token: str) -> "StreamChunk":
        """Create a normal streaming token chunk."""
        return cls(token=token)

    @classmethod
    def final_chunk(
        cls,
        finish_reason: str = "stop",
        usage: Optional[TokenUsage] = None,
        conversation_id: Optional[UUID] = None,
        message_id: Optional[UUID] = None,
    ) -> "StreamChunk":
        """Create the final chunk for a stream."""
        return cls(
            token=None,
            finish_reason=finish_reason,
            usage=usage,
            conversation_id=conversation_id,
            message_id=message_id,
        )